# Site settings
title: WhirlyGlobe-Maply
email: contact@mousebirdconsulting.com
description: > # this means to ignore newlines until "baseurl:"
  An open source geospatial display toolkit for iOS and Android.

baseurl: "/WhirlyGlobe-Maply-Site"
url: "http://mousebird.github.io/"
twitter_username: mousebirdc
github_username:  mousebird

# Conversion
markdown:    kramdown
highlighter: pygments
